apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: listmonk
spec:
  secretName: tls-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'lm.alanw.ai'
  dnsNames:
  - 'lm.alanw.ai'
