apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: listmonk-secrets
spec:
  provider: vault
  secretObjects:
  - secretName: listmonk-secrets
    type: Opaque
    data:
      - key: LISTMONK_app__admin_username
        objectName: LISTMONK_app__admin_username
      - key: LISTMONK_app__admin_password
        objectName: LISTMONK_app__admin_password
      - key: LISTMONK_db__user
        objectName: LISTMONK_db__user
      - key: LISTMONK_db__password
        objectName: LISTMONK_db__password
  parameters:
    roleName: listmonk
    vaultAddress: https://vlt.rwx.dev
    vaultKubernetesMountPath: k8s-skydive
    objects: |
      - objectName: LISTMONK_app__admin_username
        secretPath: secrets/data/listmonk
        secretKey: LISTMONK_app__admin_username
      - objectName: LISTMONK_app__admin_password
        secretPath: secrets/data/listmonk
        secretKey: LISTMONK_app__admin_password
      - objectName: LISTMONK_db__user
        secretPath: secrets/data/listmonk
        secretKey: LISTMONK_db__user
      - objectName: LISTMONK_db__password
        secretPath: secrets/data/listmonk
        secretKey: LISTMONK_db__password