apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: listmonk

labels:
  - includeSelectors: true
    pairs:
      app: listmonk

images:
  - name: listmonk-image
    newName: listmonk/listmonk
    newTag: latest

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: listmonk-env
    envs:
      - config/listmonk.env